name: Build
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # env:
    #   BOTTOKEN: ${{ secrets.BOTTOKEN }}
    #   WEBEX_ACCESS_TOKEN: ${{ secrets.WEBEX_ACCESS_TOKEN }}
    #   WEBEX_WEBHOOK_SECRET: ${{ secrets.WEBEX_WEBHOOK_SECRET }}
    #   NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    #   PORT: ${{ secrets.PORT }}
    #   S3_REGION: ${{ secrets.S3_REGION }}
    #   S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    #   S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
    #   S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    #   CLIENT_ID: ${{ secrets.CLIENT_ID }}
    #   CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    #   APP_KEY: ${{ secrets.APP_KEY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install ngrok
        run: npm install ngrok -g
      
      - name: Start ngrok and update .env
        run: |
          # Start ngrok in background
          ngrok http ${{ secrets.PORT }} --authtoken ${{ secrets.NGROK_AUTH_TOKEN }} &
          
          # Wait for ngrok to start
          sleep 5
          
          # Get ngrok public URL
          NGROK_URL=$(curl http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          # Update .env file with new ngrok URL
          sed -i "s|WEBHOOKURL=.*|WEBHOOKURL=\"$NGROK_URL\"|" .env
          
          echo "Updated WEBHOOKURL to $NGROK_URL"

      - name: Start application
        run: node index.js
      