name: Test Docker Build and Run

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t migrnwbot .

      - name: Run Docker Container & Test
        run: |
          # Run container in detached mode
          docker run -d --name test-container -p 5000:5000 migrnwbot
          # Wait a few seconds for the container to start
          sleep 5
          # Test that the container is responding on port 5000
          curl -f http://localhost:5000 || (echo "Container did not respond" && exit 1)
